---
# Ansible Inventory for Week 3: 3-Tier Application with RDS and ALB
# Updated with actual EC2 instance details

all:
  children:
    three_tier_app:
      hosts:
        app-server-1:
          # This will be overridden by host_vars/app-server-1.yml
          
      vars:
        # Environment configuration
        environment: "dev"
        project_name: "3tier-app"
        
        # Application configuration
        node_env: "production"
        app_port: 3000
        
        # Monitoring configuration
        cloudwatch_namespace: "3TierApp/Week3"
        cloudwatch_log_group: "/aws/ec2/3tier-app"
        
        # Feature flags
        enable_sticky_sessions: false
        stop_local_mysql: false
        update_database_config: true
        
        # Nginx configuration
        server_name: "_"  # Accept all hostnames
        
        # Rate limiting
        rate_limit_window: 900000  # 15 minutes
        rate_limit_max: 100
        
        # CORS settings
        cors_origin: "*"  # Restrict this in production
        
        # Logging
        log_level: "info"
        
        # SSL/TLS (for future HTTPS setup)
        enable_ssl: false
        ssl_cert_path: ""
        ssl_key_path: ""
